### ISSUE TITLE
Add Ninja Generator Support on Windows

### ISSUE THREAD

**Issue by mchagneux** [tu-studio/anira#2]
Hi, 

With MSVC, I'm trying to build the repo but when I launch the .exe it can't find the anira.dll file. I see that it's there in the build folder, is an additional step I'm missing ? I've tried running  `cmake --install build` afterwards but it doesn't work. Also, when disabling `BUILD_SHARED_LIBS` I get linker errors for undefined symbols.

Thanks in advance!

**Comment by vackva** [comment]
Hi @mchagneux! Thanks for reporting this issue!

I'll be looking into this over the next few days. In the meantime, please manually copy the ```anira.dll``` file to the same directory as your executable - this should resolve the issue for now. You should find the ```anira.dll``` file within your cmake build folder.

To help me better understand the problem, could you please provide all the commands you used during the build process?

**Comment by mchagneux** [comment]
Hi again, 

Well, I'm using the CMake extension on VSCode, so I'm not exactly writing any CMake command, but the kit I've chosen is MSVC in Release mode (from VS2022 Build Tools), using Ninja as generator. My end goal is to integrate anira into my project but I have this problem on the original anira repo when trying to build from the untouched CMakeLists.txt from the root folder.

**Comment by vackva** [comment]
Hi, we have updated the windows cmake build and added support for the Ninja generator on Windows - could you please check out the latest version on main or use tag 0.1.2 and confirm that the build works?

Thanks again for reporting the issue!

**Comment by mchagneux** [comment]
This works ! Thanks a ton.
